db:
  image: mysql:5.7
  container_name: 'mysql'
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
    - MYSQL_DATABASE=my_db_example

rabbitmq:
  image: rabbitmq:management
  container_name: 'rabbitmq'
  ports:
    - "5672:5672"
    - "15672:15672"